### ISSUE TITLE
연속 중력전환시 카메라 밖으로 나감

### ISSUE THREAD

**Issue by joecho1119** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-17#84]
중력 전환 연속적으로 실행할 시 카메라가 복도 밖으로 나감

**Comment by suzyvaque** [comment]
PR #90 : 중력전환시 camera가 벽 밖으로 나가는 버그 확인 -> cameramanager의 shiftToFront가 Wall 인 경우에만 동작하므로 corridor의 x, y, z 범위 구해서 그 안으로 Clamp하도록 로직 수정
