### ISSUE TITLE
플레이어 파이프 뚫음

### ISSUE THREAD

**Issue by kwonlauren** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-17#85]
**💣 Describe the bug**
처음에 플레이어가 벽을 뚫었던 것처럼, 플레이어가 파이프를 뚫고 지나간다

**🔗 To Reproduce**
플레이어가 적절한 높이에서 파이프 앞으로 지나가려고 계속 W를 누르면 뚫고 지나가진다

**🛡️ Expected behavior**
파이프가 플레이어 앞에 있으면 플레이어가 지나가지 못한다

**❕ Screenshots**
n.a

**⚙️ Additional context**
플레이어가 벽을 뚫는 문제를 Raycast로 해결한 것처럼, 이를 더 촘촘히해서 해결 가능할 것으로 기대

**Comment by suzyvaque** [comment]
PR#90 : 중력전환시 camera가 벽 밖으로 나가는 버그 확인 -> cameramanager의 shiftToFront가 Wall 인 경우에만 동작하므로 corridor의 x, y, z 범위 구해서 그 안으로 Clamp하도록 로직 수정
