### ISSUE TITLE
[Bug] Missing Prefab/Asset in Scene

### ISSUE THREAD

**Issue by suzyvaque** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-17#86]
**💣 Describe the bug**
Player, Maze, UI 프리팹이 Scene에 제대로 적용돼 있지 않는 이슈

**🔗 To Reproduce**
제 로컬에서만 발생하는 문제같습니다. Main에서 pull 후 Scene을 load했을 때 Player 프리팹의 astronaut이나 Maze Prefab과 관련해 Missing Asset이 있다는 에러 메시지가 뜹니다. UI 프리팹은 Missing은 아니지만 Scene에서 마찬가지로 보이지 않음 (다른 이슈일 수도)

**🛡️ Expected behavior**
프리팹이 Scene에서 보여야 함.

**❕ Screenshots**
Tutorial Scene simple maze
![image](https://github.com/user-attachments/assets/3d15d31e-1893-4f23-9f63-fd8f4c06233c)
Stage 2-1 Scene container
![image](https://github.com/user-attachments/assets/60ba04d1-ddd1-4d1d-a5c7-49230bba9afa)

**⚙️ Additional context**
git ignore 문제로 예상됨

**Comment by jeheon1231** [comment]
제가 파일 열어봤을 때는 Maze Prefab이 잘 보입니다. 무슨 이유일까요?

**Comment by suzyvaque** [comment]
앞서 Player Prefab 이슈는 .blender 파일에 의존하고 있어서, 블렌더가 외부 경로에 설치된 경우 유니티에서 블렌더를 인식하지 못해 prefab이 보이지 않는 문제로 확인됐습니다. 그래서 .blend 파일을 export한 .fbx 파일로 해당 prefab을 재형성해 문제를 해결했습니다.

저도 stage 1의 maze는 보이는데 Tutorial Scene의 Simple Maze, 그리고 추가로 Stage 2-1의 container가 안 보이는 상태입니다. 비슷한 문제로 추측되는데 만약 두 물체가 blender 파일을 기반으로 형성됐다면 fbx 파일로 대체해주실 수 있을까요?
