### ISSUE TITLE
[BUG] Stage2에서 심한 렉걸림

### ISSUE THREAD

**Issue by kwonlauren** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-17#89]
**💣 Describe the bug**
Stage2-2가 특히 렉이 너무 많이 걸려서 정상적인 플레이가 힘듭니다 (제 노트북 사양문제인지.. 다른 스테이지는 잘 되는데 얘가 렉이 심하네요)

**🔗 To Reproduce**
노트북에서 Stage2-2를 실행

**🛡️ Expected behavior**
렉이 안걸리기..

**❕ Screenshots**

https://github.com/user-attachments/assets/9e7619fe-0c10-4ed2-84a6-5e68e3484a3d

**⚙️ Additional context**
Stage2-2가 다른 씬의 약 두배 길이로 확인됩니다. 두 개의 씬으로 나누면 좋을 것 같습니다!

**Comment by suzyvaque** [comment]
Stage 2-1도 렉 걸림이 심합니다.
