### ISSUE TITLE
[BUG] Stage 1-1에서 물병이 복도 뚫음

### ISSUE THREAD

**Issue by suzyvaque** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-17#91]
**💣 Describe the bug**
Stage 1-1에서 중력 전환 시, 물병이 떨어지며 복도 바깥까지 계속 떨어지는 현상이 발생합니다.

**🔗 To Reproduce**
Stage 1-1에서 선반 앞쪽으로 이동 후 1 눌러 중력 전환

**🛡️ Expected behavior**
바닥에 부딪혀서 멈춰야 함

**❕ Screenshots**

https://github.com/user-attachments/assets/0362fba9-9ff9-4c2f-85f1-d14b95f4417a

**⚙️ Additional context**
Add any other context about the problem here. Your assumptions of why such issue happened, etc.

**Comment by jeheon1231** [comment]
해결 완료했습니다
