### ISSUE TITLE
[BUG] is ground 아닐 때도 걷는 소리 남

### ISSUE THREAD

**Issue by suzyvaque** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-17#96]
**💣 Describe the bug**
플레이어가 공중에 떠서 이동할 때도 걷는 소리가 계속 남.

**🔗 To Reproduce**
예를 들어서 방향키 누른 상태에서 점프

**⚙️ Additional context**
is ground 아닐 때는 점프 소리 안 나게 할 수 있다면 그렇게 수정

**Comment by jeheon1231** [comment]
해결했습니다

**Comment by jeheon1231** [comment]
점프 소리는 아직 해결 안 됨

**Comment by suzyvaque** [comment]
수정됨
